"""rename active to is_active in products

Revision ID: 1e3e14f73d18
Revises: 251a1c682f13
Create Date: 2025-12-18 12:01:57.095001
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1e3e14f73d18'
down_revision = '251a1c682f13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
