"""create products table

Revision ID: 24582ffeebca
Revises: dff15d422e87
Create Date: 2025-12-18 11:40:36.984815
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '24582ffeebca'
down_revision = 'dff15d422e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
