"""create products table

Revision ID: 251a1c682f13
Revises: 24582ffeebca
Create Date: 2025-12-18 11:50:56.107611
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '251a1c682f13'
down_revision = '24582ffeebca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
