"""create refresh tokens table

Revision ID: 396130cc0bbf
Revises: 04484f3d4deb
Create Date: 2025-12-18 13:09:00.181355
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '396130cc0bbf'
down_revision = '04484f3d4deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=False))
    op.add_column('products', sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('products', sa.Column('tax_code', sa.String(length=10), nullable=False))
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('products', sa.Column('dian_product_code', sa.String(length=50), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'price')
    op.drop_column('products', 'code')
    op.drop_column('products', 'iva')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('iva', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('products', 'dian_product_code')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'tax_code')
    op.drop_column('products', 'base_price')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###
