"""create products table

Revision ID: dff15d422e87
Revises: 36cf27411979
Create Date: 2025-12-18 11:35:03.835776
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dff15d422e87'
down_revision = '36cf27411979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
